ffmpeg_audio_command:
  - /usr/local/bin/ffmpeg
  - -loglevel 
  - error
  - -re
  - -vn
  - -f
  - lavfi
  - -i
  - anullsrc=channel_layout=stereo:sample_rate=44100
  - -f
  - s16le
  - -probesize 
  - '32'
  - -flags
  - low_delay
  - -fflags
  - nobuffer
  - -ar
  - '44100'
  - -ac
  - '2'
  - -i
  - 
  - -filter_complex
  - "[1:a][0:a]amix=inputs=2:duration=longest"
  - -max_delay 
  - '0'
  - -fps_mode
  - drop
  - -acodec
  - aac
  - -ar
  - '16000' 
  - -rtmp_buffer
  - '0'
  - -f
  - rtsp
  - {{ rtsp_url_placeholder }}

ffmpeg_video_command:
  - /usr/local/bin/ffmpeg
  - -loglevel 
  - error
  - -vsync
  - '0'
  - -rtsp_transport
  - udp
  - -max_delay
  - '0'
  - -flags
  - low_delay
  - -fflags
  - nobuffer
  - -probesize
  - 100M
  - -c:v
  - h264
  - -i
  - {{ rtsp_url_placeholder }}
  - -f
  - image2pipe
  - -fps_mode
  - drop
  - -preset:v
  - ultrafast   # 设置编码速度为ultrafast
  - -tune:v
  - zerolatency
  - -q:v
  - '0'
  - '-'
