use_gpu: True
gpu_mem: 500
warmup: True
image_dir: None
det_algorithm:  DB
det_limit_side_len: 960
det_limit_type:  max
det_db_thresh:  0.3
det_db_box_thresh:  0.6
det_db_unclip_ratio:  1.5
max_batch_size:  10
use_dilation:  False
det_db_score_mode:  "fast"
rec_algorithm:  'CRNN'
rec_image_inverse:  True
rec_image_shape:  "3, 48, 640"
rec_char_type:  'ch'
rec_batch_num:  6
max_text_length:  25
use_space_char:  True
drop_score:  0.5
limited_max_width:  1280
limited_min_width:  16
use_angle_cls:  True
cls_image_shape:  "3, 48, 192"
label_list:  ['0', '180']
cls_thresh:  0.9
cls_yaml_path: 
