virtual_camera_source: /home/portable-00/VisionCopilot/pharmacy/20240313_160556/20240313_160556.mp4
onnx_path: /home/portable-00/VisionCopilot/pharmacy/checkpoints/rtmdet/rtmdet_nano_8xb32-300e_hand-267f9c8f
